# Generated by Django 3.2.6 on 2021-08-15 04:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Judul')),
                ('instruction', ckeditor_uploader.fields.RichTextUploadingField(help_text='Tuliskan instruksi yang menjelaskan tentang quiz ini.', verbose_name='Instrukti')),
            ],
        ),
    ]
