# Generated by Django 3.2.6 on 2021-08-26 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missing_object', '0003_alter_missingobject_background_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tuliskan nama dari obyek gambar yang diunggah.', max_length=220, verbose_name='Nama')),
                ('picture', models.ImageField(upload_to='files/pictures/%Y/%m/%d')),
                ('missing_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missing_object.missingobject', verbose_name='Mencari Obyek')),
            ],
        ),
    ]
