# Generated by Django 3.2.6 on 2021-08-26 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missing_object', '0004_imageobject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageobject',
            options={'verbose_name': 'Obyek Gambar', 'verbose_name_plural': 'Obyek Gambar'},
        ),
        migrations.AlterModelOptions(
            name='missingobject',
            options={'verbose_name': 'Pencarian Gambar', 'verbose_name_plural': 'Pencarian Gambar'},
        ),
        migrations.AlterField(
            model_name='imageobject',
            name='missing_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missingobjects', to='missing_object.missingobject', verbose_name='Mencari Obyek'),
        ),
    ]
