# Generated by Django 3.2.6 on 2021-08-26 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missing_object', '0005_auto_20210826_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageobject',
            name='missing_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageobjects', to='missing_object.missingobject', verbose_name='Mencari Obyek'),
        ),
    ]
