# Generated by Django 3.2.6 on 2021-08-14 07:16

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Judul')),
                ('max_question', models.IntegerField(default=10, help_text='Masukan jumlah maksimal dari pertanyaan pada quiz ini.', verbose_name='Maksimal Pertanyaan')),
                ('instruction', ckeditor_uploader.fields.RichTextUploadingField(help_text='Tuliskan instruksi yang menjelaskan tentang quiz ini.', verbose_name='Instrukti')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(help_text='Warna yang dipilih akan menjadi warna latar pada quiz ini.', max_length=20, verbose_name='Warna Latar')),
                ('button_color', models.CharField(help_text='Warna yang dipilih akan menjadi warna tombol pilihan jawaban pada quiz ini.', max_length=20, verbose_name='Warna Tombol')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Tuliskan pertanyaan disini', verbose_name='Pertanyaan')),
                ('quiz', models.ManyToManyField(blank=True, to='quiz.Quiz', verbose_name='Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Tuliskan jawaban yang akan muncul pada pertanyaan.', verbose_name='Konten')),
                ('is_correct', models.BooleanField(default=False, help_text='Centang jika ini jawaban yang benar.', verbose_name='Jawaban Benar')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question', verbose_name='Pertanyaan')),
            ],
        ),
    ]
