# Generated by Django 3.2.6 on 2021-08-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210815_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='background_color',
            field=models.CharField(choices=[('bg-default', 'Coklat'), ('bg-primary', 'Hijau Telur Asin'), ('bg-info', 'Biru Awan'), ('bg-success', 'Hijau Terang'), ('bg-warning', 'Kuning Terang'), ('bg-danger', 'Merah Terang')], default='bg-primary', help_text='Warna yang dipilih akan menjadi warna latar pada quiz ini.', max_length=20, verbose_name='Warna Latar'),
        ),
    ]
