# Generated by Django 3.2.6 on 2021-08-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20210826_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Jawaban', 'verbose_name_plural': 'Jawaban'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Pertanyaan', 'verbose_name_plural': 'Pertanyaan'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quiz'},
        ),
    ]
