# Generated by Django 3.2.9 on 2022-01-22 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0206a4b1-43d4-4aac-953d-a9bf04a28c37'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='Blender File')),
                ('user_name', models.CharField(blank=True, help_text='optional', max_length=255, null=True, verbose_name='Your Name')),
                ('state', models.CharField(choices=[('prepare', 'Prepare'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], default='prepare', max_length=255, verbose_name='Render State')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
