# Generated by Django 3.2.9 on 2021-11-09 10:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('prepare', 'Prepare'), ('success', 'Success'), ('failed', 'Failed')], default='prepare', max_length=255, verbose_name='Render State'),
        ),
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(upload_to='uploads/', verbose_name='Blender File'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b5122ec9-8f67-48e5-9533-2e55eb301e3b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='renderresult',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2988b5e7-a486-4882-9b52-1de1c68424d4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
