# Generated by Django 3.2.9 on 2022-01-26 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blender', '0002_auto_20220126_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ad312c68-4a90-4530-8898-3202786c4635'), editable=False, primary_key=True, serialize=False),
        ),
    ]
