# Generated by Django 3.2.9 on 2022-01-13 02:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blender', '0002_auto_20211109_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7b26e7c4-2c83-4b0a-a72b-2f928ffbfa09'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('prepare', 'Prepare'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], default='prepare', max_length=255, verbose_name='Render State'),
        ),
        migrations.AlterField(
            model_name='renderresult',
            name='id',
            field=models.UUIDField(default=uuid.UUID('92104310-c4c2-46b7-b9c3-eea30bb3d750'), editable=False, primary_key=True, serialize=False),
        ),
    ]
