# Generated by Django 3.2.9 on 2022-01-13 02:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blender', '0003_auto_20220113_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b4a772eb-b21b-4ac7-9c1e-8ab3536cb887'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='RenderResult',
        ),
    ]
